title: Wikipedia for Slack
description: Search the sum of all human knowledge without leaving Slack.
google_analytics:
theme: jekyll-theme-cayman
is_project_page: true
github:
  owner_name: Natalia Harateh
  owner_url: https://github.com/nambatee
  repository_name: Wikipedia for Slack
  repository_url: https://github.com/nambatee/wikipedia-slackbot